// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.zingo

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_zingo_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_zingo_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_zingo"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}




















































































































































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_zingo_checksum_func_cancel_ironwood_migration(
): Short
fun uniffi_zingo_checksum_func_change_server(
): Short
fun uniffi_zingo_checksum_func_check_my_address(
): Short
fun uniffi_zingo_checksum_func_confirm(
): Short
fun uniffi_zingo_checksum_func_continue_note_splitting(
): Short
fun uniffi_zingo_checksum_func_create_new_transparent_address(
): Short
fun uniffi_zingo_checksum_func_create_new_unified_address(
): Short
fun uniffi_zingo_checksum_func_drain_orchard_to_ironwood(
): Short
fun uniffi_zingo_checksum_func_drain_status(
): Short
fun uniffi_zingo_checksum_func_execute_due_parts(
): Short
fun uniffi_zingo_checksum_func_execute_due_parts_status(
): Short
fun uniffi_zingo_checksum_func_get_balance(
): Short
fun uniffi_zingo_checksum_func_get_config_wallet_performance(
): Short
fun uniffi_zingo_checksum_func_get_developer_donation_address(
): Short
fun uniffi_zingo_checksum_func_get_latest_block_server(
): Short
fun uniffi_zingo_checksum_func_get_latest_block_wallet(
): Short
fun uniffi_zingo_checksum_func_get_messages(
): Short
fun uniffi_zingo_checksum_func_get_option_wallet(
): Short
fun uniffi_zingo_checksum_func_get_seed(
): Short
fun uniffi_zingo_checksum_func_get_spendable_balance_total(
): Short
fun uniffi_zingo_checksum_func_get_spendable_balance_with_address(
): Short
fun uniffi_zingo_checksum_func_get_total_memobytes_to_address(
): Short
fun uniffi_zingo_checksum_func_get_total_spends_to_address(
): Short
fun uniffi_zingo_checksum_func_get_total_value_to_address(
): Short
fun uniffi_zingo_checksum_func_get_transparent_addresses(
): Short
fun uniffi_zingo_checksum_func_get_ufvk(
): Short
fun uniffi_zingo_checksum_func_get_unified_addresses(
): Short
fun uniffi_zingo_checksum_func_get_value_transfers(
): Short
fun uniffi_zingo_checksum_func_get_version(
): Short
fun uniffi_zingo_checksum_func_get_wallet_save_required(
): Short
fun uniffi_zingo_checksum_func_get_wallet_version(
): Short
fun uniffi_zingo_checksum_func_get_zennies_for_zingo_donation_address(
): Short
fun uniffi_zingo_checksum_func_info_server(
): Short
fun uniffi_zingo_checksum_func_init_from_b64(
): Short
fun uniffi_zingo_checksum_func_init_from_seed(
): Short
fun uniffi_zingo_checksum_func_init_from_ufvk(
): Short
fun uniffi_zingo_checksum_func_init_logging(
): Short
fun uniffi_zingo_checksum_func_init_new(
): Short
fun uniffi_zingo_checksum_func_migration_status(
): Short
fun uniffi_zingo_checksum_func_parse_address(
): Short
fun uniffi_zingo_checksum_func_parse_ufvk(
): Short
fun uniffi_zingo_checksum_func_pause_sync(
): Short
fun uniffi_zingo_checksum_func_plan_ironwood_migration(
): Short
fun uniffi_zingo_checksum_func_plan_orchard_drain(
): Short
fun uniffi_zingo_checksum_func_poll_sync(
): Short
fun uniffi_zingo_checksum_func_reconcile_migration(
): Short
fun uniffi_zingo_checksum_func_remove_transaction(
): Short
fun uniffi_zingo_checksum_func_reschedule_parts(
): Short
fun uniffi_zingo_checksum_func_run_rescan(
): Short
fun uniffi_zingo_checksum_func_run_sync(
): Short
fun uniffi_zingo_checksum_func_save_wallet_bytes(
): Short
fun uniffi_zingo_checksum_func_send(
): Short
fun uniffi_zingo_checksum_func_set_config_wallet_to_prod(
): Short
fun uniffi_zingo_checksum_func_set_config_wallet_to_test(
): Short
fun uniffi_zingo_checksum_func_set_crypto_default_provider_to_ring(
): Short
fun uniffi_zingo_checksum_func_set_option_wallet(
): Short
fun uniffi_zingo_checksum_func_shield(
): Short
fun uniffi_zingo_checksum_func_start_ironwood_migration(
): Short
fun uniffi_zingo_checksum_func_status_sync(
): Short
fun uniffi_zingo_checksum_func_wallet_kind(
): Short
fun uniffi_zingo_checksum_func_zec_price(
): Short
fun ffi_zingo_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "zingo"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }
        
    }

    // FFI functions
    fun uniffi_zingo_fn_func_cancel_ironwood_migration(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_change_server(`serveruri`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_check_my_address(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_confirm(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_continue_note_splitting(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_create_new_transparent_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_create_new_unified_address(`receivers`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_drain_orchard_to_ironwood(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_drain_status(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_execute_due_parts(`spacingMs`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_execute_due_parts_status(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_balance(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_config_wallet_performance(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_developer_donation_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_latest_block_server(`serveruri`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_latest_block_wallet(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_messages(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_option_wallet(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_seed(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_spendable_balance_total(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_spendable_balance_with_address(`address`: RustBuffer.ByValue,`zennies`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_total_memobytes_to_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_total_spends_to_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_total_value_to_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_transparent_addresses(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_ufvk(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_unified_addresses(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_value_transfers(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_version(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_wallet_save_required(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_wallet_version(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_get_zennies_for_zingo_donation_address(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_info_server(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_init_from_b64(`datab64`: RustBuffer.ByValue,`serveruri`: RustBuffer.ByValue,`chainhint`: RustBuffer.ByValue,`performancelevel`: RustBuffer.ByValue,`minconfirmations`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_init_from_seed(`seed`: RustBuffer.ByValue,`birthday`: Int,`serveruri`: RustBuffer.ByValue,`chainhint`: RustBuffer.ByValue,`performancelevel`: RustBuffer.ByValue,`minconfirmations`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_init_from_ufvk(`ufvk`: RustBuffer.ByValue,`birthday`: Int,`serveruri`: RustBuffer.ByValue,`chainhint`: RustBuffer.ByValue,`performancelevel`: RustBuffer.ByValue,`minconfirmations`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_init_logging(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_init_new(`serveruri`: RustBuffer.ByValue,`birthday`: Int,`chainhint`: RustBuffer.ByValue,`performancelevel`: RustBuffer.ByValue,`minconfirmations`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_migration_status(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_parse_address(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_parse_ufvk(`ufvk`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_pause_sync(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_plan_ironwood_migration(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_plan_orchard_drain(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_poll_sync(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_reconcile_migration(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_remove_transaction(`txid`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_reschedule_parts(`perBucket`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_run_rescan(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_run_sync(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_save_wallet_bytes(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_send(`sendJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_set_config_wallet_to_prod(`performancelevel`: RustBuffer.ByValue,`minconfirmations`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_set_config_wallet_to_test(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_set_crypto_default_provider_to_ring(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_set_option_wallet(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_shield(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_start_ironwood_migration(`planHashHex`: RustBuffer.ByValue,`perBucket`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_status_sync(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_wallet_kind(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_zingo_fn_func_zec_price(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_zingo_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_zingo_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_zingo_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_zingo_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_zingo_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_zingo_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_zingo_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_zingo_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_zingo_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_zingo_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_zingo_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_zingo_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_zingo_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_zingo_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_zingo_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_zingo_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_zingo_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_zingo_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_zingo_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_zingo_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_zingo_checksum_func_cancel_ironwood_migration() != 44347.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_change_server() != 47175.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_check_my_address() != 14233.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_confirm() != 11704.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_continue_note_splitting() != 26867.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_create_new_transparent_address() != 37063.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_create_new_unified_address() != 56466.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_drain_orchard_to_ironwood() != 44502.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_drain_status() != 22064.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_execute_due_parts() != 55009.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_execute_due_parts_status() != 21746.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_balance() != 46672.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_config_wallet_performance() != 30117.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_developer_donation_address() != 30839.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_latest_block_server() != 961.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_latest_block_wallet() != 1269.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_messages() != 65381.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_option_wallet() != 31885.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_seed() != 17788.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_spendable_balance_total() != 15903.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_spendable_balance_with_address() != 25801.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_total_memobytes_to_address() != 37992.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_total_spends_to_address() != 1804.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_total_value_to_address() != 36757.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_transparent_addresses() != 48564.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_ufvk() != 32697.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_unified_addresses() != 48132.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_value_transfers() != 29747.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_version() != 39261.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_wallet_save_required() != 51885.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_wallet_version() != 27365.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_get_zennies_for_zingo_donation_address() != 46203.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_info_server() != 9708.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_init_from_b64() != 26833.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_init_from_seed() != 58185.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_init_from_ufvk() != 19876.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_init_logging() != 36145.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_init_new() != 65130.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_migration_status() != 14110.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_parse_address() != 37603.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_parse_ufvk() != 59749.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_pause_sync() != 1407.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_plan_ironwood_migration() != 49625.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_plan_orchard_drain() != 34771.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_poll_sync() != 35296.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_reconcile_migration() != 36661.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_remove_transaction() != 54006.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_reschedule_parts() != 2084.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_run_rescan() != 52086.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_run_sync() != 36295.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_save_wallet_bytes() != 35261.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_send() != 12451.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_set_config_wallet_to_prod() != 27284.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_set_config_wallet_to_test() != 52964.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_set_crypto_default_provider_to_ring() != 6088.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_set_option_wallet() != 19181.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_shield() != 33728.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_start_ironwood_migration() != 47149.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_status_sync() != 2462.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_wallet_kind() != 56355.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zingo_checksum_func_zec_price() != 16513.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}





sealed class ZingolibException(message: String): kotlin.Exception(message) {
        
        class LightclientNotInitialized(message: String) : ZingolibException(message)
        
        class LightclientLockPoisoned(message: String) : ZingolibException(message)
        
        class Panic(message: String) : ZingolibException(message)
        
        class Save(message: String) : ZingolibException(message)
        
        class Init(message: String) : ZingolibException(message)
        
        class Sync(message: String) : ZingolibException(message)
        
        class Rescan(message: String) : ZingolibException(message)
        
        class Read(message: String) : ZingolibException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ZingolibException> {
        override fun lift(error_buf: RustBuffer.ByValue): ZingolibException = FfiConverterTypeZingolibError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeZingolibError : FfiConverterRustBuffer<ZingolibException> {
    override fun read(buf: ByteBuffer): ZingolibException {
        
            return when(buf.getInt()) {
            1 -> ZingolibException.LightclientNotInitialized(FfiConverterString.read(buf))
            2 -> ZingolibException.LightclientLockPoisoned(FfiConverterString.read(buf))
            3 -> ZingolibException.Panic(FfiConverterString.read(buf))
            4 -> ZingolibException.Save(FfiConverterString.read(buf))
            5 -> ZingolibException.Init(FfiConverterString.read(buf))
            6 -> ZingolibException.Sync(FfiConverterString.read(buf))
            7 -> ZingolibException.Rescan(FfiConverterString.read(buf))
            8 -> ZingolibException.Read(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: ZingolibException): ULong {
        return 4UL
    }

    override fun write(value: ZingolibException, buf: ByteBuffer) {
        when(value) {
            is ZingolibException.LightclientNotInitialized -> {
                buf.putInt(1)
                Unit
            }
            is ZingolibException.LightclientLockPoisoned -> {
                buf.putInt(2)
                Unit
            }
            is ZingolibException.Panic -> {
                buf.putInt(3)
                Unit
            }
            is ZingolibException.Save -> {
                buf.putInt(4)
                Unit
            }
            is ZingolibException.Init -> {
                buf.putInt(5)
                Unit
            }
            is ZingolibException.Sync -> {
                buf.putInt(6)
                Unit
            }
            is ZingolibException.Rescan -> {
                buf.putInt(7)
                Unit
            }
            is ZingolibException.Read -> {
                buf.putInt(8)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalUInt: FfiConverterRustBuffer<kotlin.UInt?> {
    override fun read(buf: ByteBuffer): kotlin.UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: kotlin.UInt?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<kotlin.ByteArray?> {
    override fun read(buf: ByteBuffer): kotlin.ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: kotlin.ByteArray?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}
    @Throws(ZingolibException::class) fun `cancelIronwoodMigration`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_cancel_ironwood_migration(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `changeServer`(`serveruri`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_change_server(
        FfiConverterString.lower(`serveruri`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `checkMyAddress`(`address`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_check_my_address(
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `confirm`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_confirm(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `continueNoteSplitting`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_continue_note_splitting(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `createNewTransparentAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_create_new_transparent_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `createNewUnifiedAddress`(`receivers`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_create_new_unified_address(
        FfiConverterString.lower(`receivers`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `drainOrchardToIronwood`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_drain_orchard_to_ironwood(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `drainStatus`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_drain_status(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `executeDueParts`(`spacingMs`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_execute_due_parts(
        FfiConverterULong.lower(`spacingMs`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `executeDuePartsStatus`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_execute_due_parts_status(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getBalance`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_balance(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getConfigWalletPerformance`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_config_wallet_performance(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getDeveloperDonationAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_developer_donation_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getLatestBlockServer`(`serveruri`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_latest_block_server(
        FfiConverterString.lower(`serveruri`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getLatestBlockWallet`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_latest_block_wallet(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getMessages`(`address`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_messages(
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getOptionWallet`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_option_wallet(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getSeed`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_seed(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getSpendableBalanceTotal`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_spendable_balance_total(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getSpendableBalanceWithAddress`(`address`: kotlin.String, `zennies`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_spendable_balance_with_address(
        FfiConverterString.lower(`address`),FfiConverterString.lower(`zennies`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getTotalMemobytesToAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_total_memobytes_to_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getTotalSpendsToAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_total_spends_to_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getTotalValueToAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_total_value_to_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getTransparentAddresses`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_transparent_addresses(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getUfvk`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_ufvk(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getUnifiedAddresses`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_unified_addresses(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getValueTransfers`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_value_transfers(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_version(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getWalletSaveRequired`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_wallet_save_required(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getWalletVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_wallet_version(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `getZenniesForZingoDonationAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_get_zennies_for_zingo_donation_address(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `infoServer`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_info_server(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `initFromB64`(`datab64`: kotlin.String, `serveruri`: kotlin.String, `chainhint`: kotlin.String, `performancelevel`: kotlin.String, `minconfirmations`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_init_from_b64(
        FfiConverterString.lower(`datab64`),FfiConverterString.lower(`serveruri`),FfiConverterString.lower(`chainhint`),FfiConverterString.lower(`performancelevel`),FfiConverterUInt.lower(`minconfirmations`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `initFromSeed`(`seed`: kotlin.String, `birthday`: kotlin.UInt, `serveruri`: kotlin.String, `chainhint`: kotlin.String, `performancelevel`: kotlin.String, `minconfirmations`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_init_from_seed(
        FfiConverterString.lower(`seed`),FfiConverterUInt.lower(`birthday`),FfiConverterString.lower(`serveruri`),FfiConverterString.lower(`chainhint`),FfiConverterString.lower(`performancelevel`),FfiConverterUInt.lower(`minconfirmations`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `initFromUfvk`(`ufvk`: kotlin.String, `birthday`: kotlin.UInt, `serveruri`: kotlin.String, `chainhint`: kotlin.String, `performancelevel`: kotlin.String, `minconfirmations`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_init_from_ufvk(
        FfiConverterString.lower(`ufvk`),FfiConverterUInt.lower(`birthday`),FfiConverterString.lower(`serveruri`),FfiConverterString.lower(`chainhint`),FfiConverterString.lower(`performancelevel`),FfiConverterUInt.lower(`minconfirmations`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `initLogging`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_init_logging(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `initNew`(`serveruri`: kotlin.String, `birthday`: kotlin.UInt, `chainhint`: kotlin.String, `performancelevel`: kotlin.String, `minconfirmations`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_init_new(
        FfiConverterString.lower(`serveruri`),FfiConverterUInt.lower(`birthday`),FfiConverterString.lower(`chainhint`),FfiConverterString.lower(`performancelevel`),FfiConverterUInt.lower(`minconfirmations`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `migrationStatus`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_migration_status(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `parseAddress`(`address`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_parse_address(
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `parseUfvk`(`ufvk`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_parse_ufvk(
        FfiConverterString.lower(`ufvk`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `pauseSync`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_pause_sync(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `planIronwoodMigration`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_plan_ironwood_migration(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `planOrchardDrain`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_plan_orchard_drain(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `pollSync`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_poll_sync(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `reconcileMigration`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_reconcile_migration(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `removeTransaction`(`txid`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_remove_transaction(
        FfiConverterString.lower(`txid`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `rescheduleParts`(`perBucket`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_reschedule_parts(
        FfiConverterUInt.lower(`perBucket`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `runRescan`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_run_rescan(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `runSync`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_run_sync(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `saveWalletBytes`(): kotlin.ByteArray? {
            return FfiConverterOptionalByteArray.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_save_wallet_bytes(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `send`(`sendJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_send(
        FfiConverterString.lower(`sendJson`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `setConfigWalletToProd`(`performancelevel`: kotlin.String, `minconfirmations`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_set_config_wallet_to_prod(
        FfiConverterString.lower(`performancelevel`),FfiConverterUInt.lower(`minconfirmations`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `setConfigWalletToTest`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_set_config_wallet_to_test(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `setCryptoDefaultProviderToRing`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_set_crypto_default_provider_to_ring(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `setOptionWallet`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_set_option_wallet(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `shield`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_shield(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `startIronwoodMigration`(`planHashHex`: kotlin.String, `perBucket`: kotlin.UInt?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_start_ironwood_migration(
        FfiConverterString.lower(`planHashHex`),FfiConverterOptionalUInt.lower(`perBucket`),_status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `statusSync`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_status_sync(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `walletKind`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_wallet_kind(
        _status)
}
    )
    }
    

    @Throws(ZingolibException::class) fun `zecPrice`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZingolibException) { _status ->
    UniffiLib.INSTANCE.uniffi_zingo_fn_func_zec_price(
        _status)
}
    )
    }
    


