export const GlobalConst = {
  error: 'error',
  zcash: 'zcash:',
  port80: '80',
  port443: '443',
  port9067: '9067',
  http: 'http:',
  https: 'https:',
  serverPlaceHolder: 'https://------.---:---',
  uview: 'uview',
  utestview: 'utestview',
  success: 'success',
  true: 'true',
  false: 'false',
  memoMaxLength: 511,
  platformOSios: 'ios',
  platformOSandroid: 'android',
  blocksPerBatch: 100,
  yes: 'yes',
  no: 'no',
  background: '@background',
  keyKeyChain: 'ZINGO_SEED_BIRTHDAY',
  serviceKeyChain: 'ZINGO',
};
