// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "zingo-ffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeZingoFfi.h"

@interface ZingoFfi : NSObject <NativeZingoFfiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ZingoFfi : NSObject <RCTBridgeModule>
#endif

@end