export enum MenuItemEnum {
  Wallet = 'Wallet',
  Rescan = 'Rescan',
  Settings = 'Settings',
  ChangeWallet = 'Change Wallet',
  RestoreWalletBackup = 'Restore Wallet Backup',
  SyncReport = 'Sync Report',
  FundPools = 'Fund Pools',
  Insight = 'Insight',
  LoadWalletFromSeed = 'Load Wallet From Seed',
  TipZingoLabs = 'Tip ZingoLabs',
  AddressBook = 'Address Book',
  About = 'About',
  Info = 'Info',
}
