export enum RouteEnum {
  // Stack
  LoadingApp = 'LoadingApp',
  LoadedApp = 'LoadedApp',

  Servers = 'Servers',

  MainTabs = 'MainTabs',

  // Drawer no params
  History = 'History',
  Send = 'Send',
  Receive = 'Receive',
  Faucet = 'Faucet',
  Messages = 'Messages',
  ValueTransferDetailStack = 'ValueTransferDetailStack',
  ConfirmStack = 'ConfirmStack',
  InsightStack = 'InsightStack',
  Settings = 'Settings',
  SettingsMenu = 'SettingsMenu',
  SettingsServers = 'SettingsServers',
  DebugInfo = 'DebugInfo',
  About = 'About',
  Rescan = 'Rescan',
  Info = 'Info',
  Insight = 'Insight',
  Computing = 'Computing',
  ComputingOK = 'ComputingOK',
  ComputingError = 'ComputingError',
  SyncReport = 'SyncReport',
  Pools = 'Pools',
  ContactList = 'ContactList',
  StakingHome = 'StakingHome',
  Stake = 'Stake',
  Unstake = 'Unstake',
  Distribution = 'Distribution',
  Redelegate = 'Redelegate',
  Finalizers = 'Finalizers',

  // Drawer with params
  AddressList = 'AddressList',
  ScannerAddress = 'ScannerAddress',
  ValueTransferDetail = 'ValueTransferDetail',
  MessagesAddress = 'MessagesAddress',
  MessagesAll = 'MessagesAll',
  Memo = 'Memo',
  Confirm = 'Confirm',
  Ufvk = 'Ufvk',
  Seed = 'Seed',
}
