export enum RouteEnum {
  // Loading screens
  Launching = 'Launching',
  StartMenu = 'StartMenu',
  NewSeed = 'NewSeed',
  ImportChooser = 'ImportChooser',
  ImportUfvk = 'ImportUfvk',
  WalletProgress = 'WalletProgress',
  WalletError = 'WalletError',
  Server = 'Server',
  ServerList = 'ServerList',

  // Stack
  LoadingApp = 'LoadingApp',
  LoadedApp = 'LoadedApp',

  // Drawer no params
  HomeStack = 'HomeStack',
  History = 'History',
  Send = 'Send',
  Receive = 'Receive',
  Messages = 'Messages',
  Settings = 'Settings',
  About = 'About',
  MixnetDoctor = 'MixnetDoctor',
  Rescan = 'Rescan',
  Insight = 'Insight',
  Computing = 'Computing',
  SyncReport = 'SyncReport',
  Pools = 'Pools',
  MeetIronwood = 'MeetIronwood',
  SeedBackup = 'SeedBackup',
  WalletSeed = 'WalletSeed',
  MigrationStrategy = 'MigrationStrategy',
  MigrationTransactions = 'MigrationTransactions',
  MigrationSending = 'MigrationSending',
  MigrationSplitPlan = 'MigrationSplitPlan',
  MigrationSplitting = 'MigrationSplitting',
  MigrationCadence = 'MigrationCadence',
  MigrationSchedule = 'MigrationSchedule',
  MigrationStatus = 'MigrationStatus',
  MigrationBatchSending = 'MigrationBatchSending',

  // Drawer with params
  AddressBook = 'AddressBook',
  AddressList = 'AddressList',
  ScannerAddress = 'ScannerAddress',
  ScannerUfvk = 'ScannerUfvk',
  ValueTransferDetail = 'ValueTransferDetail',
  Confirm = 'Confirm',
  Ufvk = 'Ufvk',
}
