export enum SettingsNameEnum {
  server = 'server',
  currency = 'currency',
  language = 'language',
  sendAll = 'sendAll',
  donation = 'donation',
  privacy = 'privacy',
  mode = 'mode',
  firstInstall = 'firstInstall',
  basicFirstViewSeed = 'basicFirstViewSeed',
  version = 'version',
  security = 'security',
  selectServer = 'selectServer',
  firstUpdateWithDonation = 'firstUpdateWithDonation',
  rescanMenu = 'rescanMenu',
}
