#!/usr/bin/env bash
#
# Generates app/swap/swapKitSecrets.ts from the SWAPKIT_API_KEY environment
# variable. Invoked by CI workflows that bundle JS or run Jest.
#
# Behaviour by env-var presence:
#   - SWAPKIT_API_KEY set       → overwrite the file with the real key.
#   - SWAPKIT_API_KEY unset AND file already exists → preserve as-is. This
#     stops a local developer from accidentally nuking their working key by
#     running the script with no env var set (e.g. for debugging or refresh).
#   - SWAPKIT_API_KEY unset AND file missing → write a placeholder so the
#     TypeScript still compiles and Jest still runs. The SwapKitClient
#     constructor throws on the placeholder at runtime, so any swap
#     execution path fails loudly rather than silently shipping a broken
#     APK. This branch covers external-fork PRs that cannot see secrets.
#
# The key is encoded as a JSON string before being injected into the TS file,
# which is robust against quotes, backslashes, or any other character that
# might appear in an API key.

set -euo pipefail

OUT="app/swap/swapKitSecrets.ts"

if [ -z "${SWAPKIT_API_KEY:-}" ]; then
  if [ -f "$OUT" ]; then
    echo "INFO: SWAPKIT_API_KEY not set; preserving existing $OUT" >&2
    exit 0
  fi
  KEY="replace-me-with-real-key"
else
  KEY="$SWAPKIT_API_KEY"
fi

# Use Python (always present on GitHub-hosted runners) to JSON-encode the key.
ENCODED=$(printf '%s' "$KEY" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')

cat > "$OUT" <<EOF
// Generated by scripts/ci/generate-swapkit-secrets.sh. Do not commit.
export const SWAPKIT_API_KEY = $ENCODED;
EOF

if [ "$KEY" = "replace-me-with-real-key" ]; then
  echo "WARN: SWAPKIT_API_KEY not set and $OUT did not exist; wrote placeholder" >&2
else
  echo "Wrote $OUT (key length: ${#KEY})"
fi
