#!/usr/bin/env bash
#
# Generates app/swap/swapKitSecrets.ts from the SWAPKIT_API_KEY environment
# variable. Invoked by CI workflows that bundle JS or run Jest.
#
# When SWAPKIT_API_KEY is empty (e.g. external-fork PRs that cannot see repo
# secrets), a placeholder is written instead. The TypeScript still compiles
# and Jest still runs; the SwapKitClient constructor throws at runtime if it
# detects the placeholder, so any swap execution path will fail loudly.
#
# The key is encoded as a JSON string before being injected into the TS file,
# which is robust against quotes, backslashes, or any other character that
# might appear in an API key.

set -euo pipefail

OUT="app/swap/swapKitSecrets.ts"
KEY="${SWAPKIT_API_KEY:-replace-me-with-real-key}"

# Use Python (always present on GitHub-hosted runners) to JSON-encode the key.
ENCODED=$(printf '%s' "$KEY" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')

cat > "$OUT" <<EOF
// Generated by scripts/ci/generate-swapkit-secrets.sh. Do not commit.
export const SWAPKIT_API_KEY = $ENCODED;
EOF

if [ "$KEY" = "replace-me-with-real-key" ]; then
  echo "WARN: SWAPKIT_API_KEY not set; wrote placeholder to $OUT" >&2
else
  echo "Wrote $OUT (key length: ${#KEY})"
fi
