import { PoolEnum, ValueTransferType, ValueTransferKindEnum } from '../../app/AppState';
import { RPCValueTransfersStatusEnum } from '../../app/rpc/enums/RPCValueTransfersStatusEnum';

export const mockValueTransfers: ValueTransferType[] = [
  {
    kind: ValueTransferKindEnum.Sent,
    fee: 0.0001,
    confirmations: 22,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'sent-txid-1234567890',
    time: Date.now() - 1000,
    zecPrice: 33.33,
    address: 'sent-address-1-12345678901234567890',
    amount: 0.12345678,
    memos: ['hola', '  & ', 'hello'],
  },
  {
    kind: ValueTransferKindEnum.MemoToSelf,
    fee: 0.0001,
    confirmations: 12,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'memotooself-txid-1234567890',
    time: Date.now() - 100,
    zecPrice: 33.33,
    amount: 0,
    memos: ['orchard memo', 'sapling memo'],
  },
  {
    kind: ValueTransferKindEnum.SendToSelf,
    fee: 0.0001,
    confirmations: 12,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'sendtooself-txid-1234567890',
    time: Date.now() - 100,
    zecPrice: 33.33,
    amount: 0,
  },
  {
    kind: ValueTransferKindEnum.Received,
    confirmations: 133,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'receive-txid-1234567890',
    time: Date.now() - 10,
    zecPrice: 66.66,
    amount: 0.77654321,
    poolType: PoolEnum.OrchardPool,
    memos: ['hola', '  & ', 'hello'],
  },
  {
    kind: ValueTransferKindEnum.Shield,
    fee: 0.0001,
    confirmations: 12,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'shield-txid-1234567890',
    time: Date.now(),
    zecPrice: 33.33,
    amount: 0.0009,
  },
  {
    kind: ValueTransferKindEnum.Rejection,
    fee: 0.0001,
    confirmations: 12,
    status: RPCValueTransfersStatusEnum.confirmed,
    txid: 'rejection-320-tex-txid-1234567890',
    time: Date.now(),
    zecPrice: 33.33,
    amount: 0.0009,
  },
];
