[package]
name = "rustandroid"
version = "2.0.0"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2024"

[features]
ci = []
regchest = []

[dev-dependencies]
zingolib_testutils = { workspace = true }
zingomobile_utils = { workspace = true }
regchest_utils = { workspace = true }
tokio = { workspace = true }
zcash_local_net = { git = "https://github.com/zingolabs/infrastructure.git", rev = "89cf104a2416144d1bbbae30aca02bec062d1492" }
