[workspace]
members = ["lib", "android", "ios", "zingomobile_utils"]
resolver = "2"

[workspace.dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib", rev = "zingolib_v3.0.0-rc.5" }
pepper-sync = "0.2.0"
zingolib_testutils = { git = "https://github.com/zingolabs/zingolib", rev = "zingolib_v3.0.0-rc.5", features = [
    "test_lwd_zcashd",
] }
regchest_utils = { git = "https://github.com/zingolabs/zingo-regchest", branch = "dev" }
zingomobile_utils = { path = "zingomobile_utils" }

zcash_address = "0.10"
zcash_client_backend = { version = "0.21", features = [
    "lightwalletd-tonic",
    "orchard",
    "transparent-inputs",
    "tor",
] }
zcash_encoding = "0.3"
zcash_keys = { version = "0.12", features = [
    "transparent-inputs",
    "sapling",
    "orchard",
] }
zcash_note_encryption = "0.4"
zcash_proofs = "0.26"
zcash_protocol = "0.7"
zcash_transparent = "0.6"

zebra-chain = "5.0.0"

zingo_common_components = "0.2.0"

bip0039 = { version = "0.13", features = ["rand"] }
zip32 = "0.2.0"
uniffi = "0.29"
tokio = "1"
rustls = { version = "0.23", features = ["ring"] }
serde_json = "1"
android_logger = "0.11"
base64 = "0.22"
env_logger = "0.10.0"
http = "1"
hex = "0.4"
json = "0.12"
lazy_static = "1.4.0"
log = "0.4"
uniffi_build = "0.29"
thiserror = "1"
once_cell = "1"

[profile.release]
debug = 1
lto = false
codegen-units = 1
overflow-checks = false

[profile.test]
opt-level = 3
debug = false
