[workspace]
members = ["lib", "android", "ios", "zingomobile_utils"]
resolver = "2"

[workspace.dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib", default-features = true, branch = "deps/update-lrz-crates_02" }
pepper-sync = { git = "https://github.com/zingolabs/zingolib", branch = "deps/update-lrz-crates_02" }
regchest_utils = { git = "https://github.com/zingolabs/zingo-regchest", branch = "dev" }
zingomobile_utils = { path = "zingomobile_utils" }

zcash_primitives = { git = "https://github.com/zcash/librustzcash", rev = "d387aed7e04e881dbe30c6ff8b26a96c834c094b" }
zcash_keys = { git = "https://github.com/zcash/librustzcash", rev = "d387aed7e04e881dbe30c6ff8b26a96c834c094b", features = [
    "transparent-inputs",
    "sapling",
    "orchard",
] }
zcash_address = { git = "https://github.com/zcash/librustzcash", rev = "d387aed7e04e881dbe30c6ff8b26a96c834c094b" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash", rev = "d387aed7e04e881dbe30c6ff8b26a96c834c094b", features = [
    "local-consensus",
] }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash", rev = "d387aed7e04e881dbe30c6ff8b26a96c834c094b", features = [
    "lightwalletd-tonic",
    "orchard",
    "transparent-inputs",
    "tor",
] }

bip0039 = { version = "0.12", features = [ "rand" ] }
uniffi = "0.29"
tokio = { version = "1.24", features = ["full"] }
rustls = { version = "0.23", features = ["ring"] }
serde_json = "1"
android_logger = "0.11"
base64 = "0.22"
env_logger = "0.10.0"
http = "1.1.0"
hex = "0.4"
json = "0.12.4"
lazy_static = "1.4.0"
log = "0.4"
uniffi_build = "0.29"

[patch.crates-io]
zcash_script = { git = "https://github.com/juanky201271/zcash_script", branch = "fixing_cross_compiling_32_bits_v_0.3.2" }

[profile.release]
debug = 1
lto = false
codegen-units = 1
overflow-checks = false

[profile.test]
opt-level = 3
debug = false
