// Generated by uniffi-bindgen-react-native
#include "zingo-ffi.h"
#include "generated/zingo.hpp"

namespace zingoffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeZingo::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}