name: Android Ubuntu FOSS Script Artifact

on:
  workflow_call:
    inputs:

env:
  REPO-OWNER: ${{ github.repository_owner }}
  ZINGO_JKS_BASE64: ${{ secrets.ZINGO_JKS_BASE64 }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  android-ubuntu-foss-script-artifact:
    name: Android Ubuntu Foss Script Artifact
    runs-on: ubuntu-24.04
    container:
      image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: init
        run: |
          sudo chown -R $(whoami) .
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo sdkmanager "platforms;android-31"
          sudo sdkmanager "platform-tools" "build-tools;31.0.0"
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          ls -la /opt/android-sdk/platforms
          rm -rf /opt/android-sdk/platforms/android-30

      - name: Node JS & build script
        working-directory: rust/lib
        run: |
          sudo apt-get update && apt-get install pkg-config build-essential apt-utils libpixman-1-dev \
            libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
          sudo curl -Lo node.tar.gz https://nodejs.org/dist/v22.18.0/node-v22.18.0-linux-x64.tar.gz
          sudo echo "eb5b031bdd728871c3b9a82655dbfa533bc262c0b6da1d09a86842430cef07d4 node.tar.gz" | sha256sum -c -
          sudo tar xzf node.tar.gz --strip-components=1 -C /usr/local/
          sudo npm install --global yarn
          sudo bash ../build_fdroid.sh

      - name: Yarn install
        run: npm_config_build_from_source=true sudo yarn install

      - name: Yarn remove vision-camera library
        run: sudo yarn remove react-native-vision-camera || true

      - name: local.properties Android SDK path
        working-directory: android
        run: sudo echo "sdk.dir=/opt/android-sdk" > local.properties

      - name: Gradle clean
        working-directory: android
        run: sudo ./gradlew clean

      - name: Copy native & kotlin libs
        working-directory: rust/lib
        run: |
          sudo mkdir -p ../../android/app/src/main/jniLibs/arm64-v8a
          sudo mkdir -p ../../android/app/src/main/jniLibs/armeabi-v7a
          sudo mkdir -p ../../android/app/src/main/jniLibs/x86
          sudo mkdir -p ../../android/app/src/main/jniLibs/x86_64
          sudo mkdir -p ../../android/app/build/generated/source/uniffi/debug/java/uniffi/zingo
          sudo mkdir -p ../../android/app/build/generated/source/uniffi/release/java/uniffi/zingo
          sudo cp /opt/jniLibs/x86_64/libuniffi_zingo.so ../../android/app/src/main/jniLibs/x86_64/libuniffi_zingo.so
          sudo cp /opt/jniLibs/x86/libuniffi_zingo.so ../../android/app/src/main/jniLibs/x86/libuniffi_zingo.so
          sudo cp /opt/jniLibs/armeabi-v7a/libuniffi_zingo.so ../../android/app/src/main/jniLibs/armeabi-v7a/libuniffi_zingo.so
          sudo cp /opt/jniLibs/arm64-v8a/libuniffi_zingo.so ../../android/app/src/main/jniLibs/arm64-v8a/libuniffi_zingo.so
          sudo cp /opt/jniLibs/kotlin/zingo.kt ../../android/app/build/generated/source/uniffi/debug/java/uniffi/zingo/zingo.kt
          sudo cp /opt/jniLibs/kotlin/zingo.kt ../../android/app/build/generated/source/uniffi/release/java/uniffi/zingo/zingo.kt

      - name: Decoding Keystore File & Save
        working-directory: android/app
        run: sudo echo "${{ env.ZINGO_JKS_BASE64 }}" | base64 --decode > Zingo.jks

      - name: Set up Keystore properties
        working-directory: android
        run: |
          sudo echo "KEYSTORE_PASSWORD=${{ env.KEYSTORE_PASSWORD }}" > local.zingo.jks.properties
          sudo echo "KEY_ALIAS=${{ env.KEY_ALIAS }}" >> local.zingo.jks.properties
          sudo echo "KEY_PASSWORD=${{ env.KEY_PASSWORD }}" >> local.zingo.jks.properties

      - name: Build release Signed APK Artifact
        working-directory: android
        run: |
          export SOURCE_DATE_EPOCH=1710000000
          export ZERO_AR_DATE=1
          sudo ./gradlew assembleRelease

      - name: Strip Non-determinstic Metadata
        working-directory: android/app/build/outputs/apk/release
        run: |
          sudo apt-get install strip-nondeterminism
          sudo strip-nondeterminism app-release.apk

      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
