[package]
name = "zingo"
version = "2.0.0"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2024"

[dependencies]
zingolib = { workspace = true }
pepper-sync = { workspace = true }

zcash_keys = { workspace = true }
zcash_address = { workspace = true }
zcash_protocol = { workspace = true }

rusqlite = { version = "0.37.0", features = ["bundled"] }
zingo_common_components = { workspace = true }

http = { workspace = true }
json = { workspace = true }
lazy_static = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
android_logger = { workspace = true }
log = { workspace = true }
uniffi = { workspace = true, features = ["cli"] }
tokio = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }
bip0039 = { workspace = true }
ed25519-zebra = { workspace = true }
zip32 = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }
zingo-netutils = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.21", default-features = false }
rustls-platform-verifier = "0.6"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = { workspace = true }

[build-dependencies]
uniffi_build = { workspace = true, features = ["builtin-bindgen"] }

[lib]
crate-type = ["cdylib", "staticlib"]
name = "zingo"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
