[package]
name = "zingo"
version = "2.0.0"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
zingolib = { workspace = true }
pepper-sync = { workspace = true }
http = "1.1.0"
json = "0.12"
lazy_static = "1.4.0"
base64 = "0.22"
android_logger = "0.11"
log = "0.4"
uniffi = { workspace = true, features = ["cli"] }
tokio = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }

zcash_primitives = { workspace = true }
zcash_keys = { workspace = true }
zcash_address = { workspace = true }
zcash_protocol = { workspace = true }
zcash_client_backend = { workspace = true }

[build-dependencies]
uniffi_build = { version = "0.29", features = ["builtin-bindgen"] }

[lib]
crate-type = ["cdylib", "staticlib"]
name = "zingo"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
