[package]
name = "rustios"
version = "2.0.0"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2024"

[features]
ci = []

[dev-dependencies]
zingolib = { workspace = true , features = [
    "testutils",
] }
pepper-sync = { workspace = true }
zingolib_testutils = { workspace = true }
zingomobile_utils = { workspace = true }
json = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
rustls = { workspace = true }
