[package]
name = "rustios"
version = "2.0.0"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2024"

[features]
ci = []
regchest = []

[dev-dependencies]
zingolib_testutils = { workspace = true }
zingomobile_utils = { workspace = true }
regchest_utils = { workspace = true }
tokio = { workspace = true }
