name: Android test

on:
  workflow_call:
    inputs:
      timestamp:
        required: true
        type: string
      cache-key:
        required: true
        type: string
    
env:
  CACHE-KEY: ${{ inputs.cache-key }}
  TIMESTAMP: ${{ inputs.timestamp }}
  REPO-OWNER: ${{ github.repository_owner }}
  RUSTFLAGS: -D warnings

jobs:
  android-build-test-artifacts:
    name: Android Build test artifacts
    runs-on: macos-13
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Install protoc
        run: brew install protobuf

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Build and archive tests
        working-directory: ./rust
        run: cargo nextest archive --verbose --features "ci regchest" --archive-file nextest-archive.tar.zst

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: nextest-archive
          path: ./rust/nextest-archive.tar.zst

  pre-build-android:
    name: Pre-Build Android Gradlew
    needs: [ android-build-test-artifacts ]
    runs-on: macos-13
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV
            
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Rust toolchain stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}

      - name: Yarn
        run: yarn

      - name: Pre-build
        working-directory: ./android
        run: ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust
