name: Create cache key

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key"
        value: ${{ jobs.create-cache-key.outputs.cache-key }}

env:
  REPO-OWNER: ${{ github.repository_owner }}

jobs:
  create-cache-key:
    name: Create cache key
    runs-on: ubuntu-24.04
    env:
      RUSTUP_HOME: ${{ github.workspace }}/.rustup
      CARGO_HOME:  ${{ github.workspace }}/.cargo
    outputs:
      cache-key: ${{ steps.create-cache-key.outputs.cache-key }}
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Cargo update for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: |
          set -euo pipefail

          TOML="rust/Cargo.toml"
          REV="${GITHUB_SHA}"

          sed -i -E "/^zingolib[[:space:]]*=/ s/(rev[[:space:]]*=[[:space:]]*\")[^\"]*(\")/\1${REV}\2/" "$TOML"

          sed -i -E "/^zingolib[[:space:]]*=/ s/(branch|tag)[[:space:]]*=[[:space:]]*\"[^\"]*\"/rev = \"${REV}\"/" "$TOML"

          first_line="$(grep -E '^zingolib[[:space:]]*=' "$TOML")"
          echo "zingolib first line => $first_line"
          echo "$first_line" | grep -q "rev = \"${REV}\""
          echo "$first_line" | grep -vqE '\b(branch|tag)[[:space:]]*='

          cd rust
          rustup default stable
          cargo update -p zingolib -p regchest_utils --aggressive

      - name: Store Cargo version
        run: echo $(cargo --version) >> rust/cargo_version.txt

      - name: Create cache key
        id: create-cache-key
        run: echo "cache-key=${{ hashFiles('rust/**/Cargo.toml', 'rust/**/Cargo.lock', 'rust/**/*.rs', 'rust/cargo_version.txt') }}" >> $GITHUB_OUTPUT
