name: IOS Integration test

on:
  workflow_call:
    inputs:
      timestamp:
        required: true
        type: string
      cache-key:
        required: true
        type: string

env:
  CACHE-KEY: ${{ inputs.cache-key }}
  TIMESTAMP: ${{ inputs.timestamp }}
  REPO-OWNER: ${{ github.repository_owner }}

jobs:
  ios-integration-test:
    name: IOS Integration test
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        test: [
          "offline_testsuite",
          "execute_sync_from_seed",
          "execute_send_from_orchard",
          "execute_currentprice_and_value_transfers_from_seed",
          "execute_sapling_balance_from_seed",
          "execute_parse_addresses"
        ]

    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Install nvm with node 22.18.0
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 22.18.0
          nvm use 22.18.0

      - name: Native rust cache
        uses: actions/cache/restore@v4
        with:
          path: rust/lib/Generated
          key: native-ios-uniffi-universal-${{ env.CACHE-KEY }}
          fail-on-cache-miss: true

      - name: Copy libs to ios folder
        working-directory: rust/lib/Generated
        run: cp ./*.* ../../../ios

      - name: Install protoc
        run: brew install protobuf

      - name: Install docker
        run: |
          brew install --head colima
          brew install --formula docker
          colima start

      - name: Colima status
        run: colima status

      - name: Grant permissions
        run: |
          sudo chmod 777 ~/.colima/default/docker.sock
          sudo chmod 777 ./scripts/ci/integration_tests_ci.sh

      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-workspaces: rust -> rust/target

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Pull regchest docker image
        run: docker pull zingodevops/regchest:010

      - name: Yarn
        run: yarn

      - name: Pod Install
        working-directory: ios
        run: pod install

      - name: Run IOS integration tests
        working-directory: ./rust
        run: cargo nextest run ios_integration::universal::${{ matrix.test }} --features "ci regchest" --verbose --release

      - name: Upload iOS test reports (.xcresult)
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-integration-reports-ios-${{ env.TIMESTAMP }}
          path: ios/build/reports/ZingoMobile-${{ env.TIMESTAMP }}.xcresult

      - name: Upload DerivedData logs (optional)
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-integration-derived-logs-ios-${{ env.TIMESTAMP }}
          path: |
            ios/build/DerivedData/Logs/Test
            ios/build/DerivedData/Logs/CrashReporter
          if-no-files-found: ignore