name: Build

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

env:
  CACHE-KEY: ${{ inputs.cache-key }}
  REPO-OWNER: ${{ github.repository_owner }}

jobs:
  ios-check-build-cache:
    name: Check build cache
    runs-on: macos-15
    outputs:
      ios-cache-found: ${{ steps.ios-set-cache-found.outputs.ios-cache-found }}
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Check if iOS xcframework cache exists
        id: ios-check-build-cache
        uses: actions/cache/restore@v6
        with:
          path: |
            ios/Zingolib.xcframework
            ios/zingo.swift
          key: native-ios-xcframework-${{ env.CACHE-KEY }}
          lookup-only: true

      - name: Set cache-found
        id: ios-set-cache-found
        run: echo "ios-cache-found=${{ steps.ios-check-build-cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT

  ios-build:
    name: Build iOS Rust xcframework
    needs: ios-check-build-cache
    if: ${{ needs.ios-check-build-cache.outputs.ios-cache-found != 'true' }}
    runs-on: macos-15
    env:
      RUSTUP_HOME: ${{ github.workspace }}/.rustup
      CARGO_HOME:  ${{ github.workspace }}/.cargo
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Cargo update for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: |
          set -euo pipefail

          TOML="rust/Cargo.toml"
          REV="${GITHUB_SHA}"

          sed -i '' -E \
            "/^zingolib[[:space:]]*=/ s/rev[[:space:]]*=[[:space:]]*\"[^\"]*\"/rev = \"${REV}\"/" \
            "$TOML"

          sed -i '' -E \
            "/^zingolib[[:space:]]*=/ s/(branch|tag)[[:space:]]*=[[:space:]]*\"[^\"]*\"/rev = \"${REV}\"/" \
            "$TOML"

          first_line="$(grep -E '^zingolib[[:space:]]*=' "$TOML")"
          echo "zingolib first line => $first_line"
          echo "$first_line" | grep -q "rev = \"${REV}\""
          echo "$first_line" | grep -vqE '\b(branch|tag)[[:space:]]*='

          cd rust
          rustup default stable
          cargo update -p zingolib --aggressive

      - name: Cargo default stable
        run: |
          rustup update
          rustup upgrade
          rustup default stable

      - name: Install bindgen-cli (needed by aws-lc-sys, ring etc.)
        run: cargo install --force --locked bindgen-cli

      - name: Install protoc
        run: brew install protobuf

      - name: Install iOS Rust targets (device + simulator)
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      # this issue is solved in bindgen 0.70
      # But we have a dependency that are using a incompatible version 0.69.
      - name: Cargo env for iOS sim (bindgen/cc)
        shell: bash
        run: |
          mkdir -p .cargo
          SDKROOT="$(xcrun --sdk iphonesimulator --show-sdk-path)"
          cat > .cargo/config.toml <<EOF
          [env]
          BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_ios_sim = "--target=arm64-apple-ios-simulator -isysroot $SDKROOT"
          CFLAGS_aarch64_apple_ios_sim = "--target=arm64-apple-ios-simulator -isysroot $SDKROOT"
          CXXFLAGS_aarch64_apple_ios_sim = "--target=arm64-apple-ios-simulator -isysroot $SDKROOT"
          EOF

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Build iOS Rust xcframework
        run: node rust/ios/build_ios.mjs

      - name: Upload xcframework artifact
        uses: actions/upload-artifact@v7
        with:
          name: native-ios-xcframework-${{ env.CACHE-KEY }}
          path: |
            ios/Zingolib.xcframework
            ios/zingo.swift

  cache-native-ios-uniffi:
    name: Cache iOS xcframework
    needs: ios-build
    runs-on: macos-15
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Download xcframework artifact
        uses: actions/download-artifact@v4
        with:
          name: native-ios-xcframework-${{ env.CACHE-KEY }}
          path: ios

      - name: Cache xcframework
        uses: actions/cache/save@v6
        with:
          path: |
            ios/Zingolib.xcframework
            ios/zingo.swift
          key: native-ios-xcframework-${{ env.CACHE-KEY }}
