name: Jest test

on:
  workflow_call:

jobs:
  jest-test:
    name: Jest test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - run: yarn

      - name: Audit dependencies
        run: yarn audit --level critical

      - run: yarn coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

